server:
  port: 8089

spring:
  datasource:
    url: jdbc:mariadb://47.107.236.20:3306/mysql?pinGlobalTxToPhysicalConnection=true
    username: root
    password: abcd1234
    type: org.apache.commons.dbcp2.BasicDataSource
    max-wait-millis: 10000
    min-idle: 5
    initial-size: 5
    validation-query: SELECT x
    connection-properties: characterEncoding=utf8
  jpa:
    database: mysql
    generateDdl: false
    showSql: true
